library(shiny)
library(ggplot2)

shinyUI(fluidPage(
  headerPanel("R.E.D. Education Data"),
  sidebarPanel(
    h6("Designed by Luo Kangshun, Andy, submitted in partial fulfillment of COURSERA Developing Data Products course."),
    h3("Pearson Education Indicator:"),
    selectInput("edi","Select Education Indicator",
                c("Average annual gross wage (US$)"="Average annual gross wage (US$)",
                  "Citations H index"="Citations H index",
                  "Corruption Perceptions Index"="Corruption Perceptions Index",
                  "GDP per capita (US$PPP)"="GDP per capita (US$PPP)",
                  "Gini index"="Gini index",
                  "Government responsibility for informing parents about school choice. Primary and lower secondary levels"="Government responsibility for informing parents about school choice. Primary and lower secondary levels",
                  "Grade 4 - TIMSS"="Grade 4 - TIMSS",
                  "Grade 8 - PISA"="Grade 8 - PISA",
                  "Grade 8 - TIMSS"="Grade 8 - TIMSS",
                  "Health Index"="Health Index",
                  "Homicide per 100,000 people"="Homicide per 100,000 people",
                  "Human Development Index"="Human Development Index",
                  "Index of school responsibility for curriculum and assessment"="Index of school responsibility for curriculum and assessment",
                  "Labour force. Tertiary attainment (%)"="Labour force. Tertiary attainment (%)",
                  "Mean socio-economic background of parents"="Mean socio-economic background of parents",
                  "Number of jailed population per 100,000 people"="Number of jailed population per 100,000 people",
                  "Overall productivity of labour (GDP at US$PPP per worker)"="Overall productivity of labour (GDP at US$PPP per worker)",
                  "Parental expectations are characterised by pressure on the school to achieve high academic standards among students"="Parental expectations are characterised by pressure on the school to achieve high academic standards among students",
                  "PIAAC- Literacy proficiency"="PIAAC- Literacy proficiency",
                  "PIAAC- Numeracy proficiency"="PIAAC- Numeracy proficiency",
                  "PIAAC average score"="PIAAC average score",
                  "PIRLS - Reading Literacy Achievement, Grade 4"="PIRLS - Reading Literacy Achievement, Grade 4",
                  "PISA - Mathematics literacy, Grade 8"="PISA - Mathematics literacy, Grade 8",
                  "PISA - Overall reading literacy, Grade 8"="PISA - Overall reading literacy, Grade 8",
                  "PISA - Science literacy, Grade 8"="PISA - Science literacy, Grade 8",
                  "Pre-primary entrance age"="Pre-primary entrance age",
                  "Public expenditure on education as % of total government expenditure"="Public expenditure on education as % of total government expenditure",
                  "Public expenditure per pupil as % of GDP per capita. All levels"="Public expenditure per pupil as % of GDP per capita. All levels",
                  "Pupil-teacher ratio. Primary school"="Pupil-teacher ratio. Primary school",
                  "Pupil-teacher ratio. Secondary school"="Pupil-teacher ratio. Secondary school",
                  "Recorded unemployment (%)"="Recorded unemployment (%)",
                  "School life expectancy (Primary to tertiary)"="School life expectancy (Primary to tertiary)",
                  "School responsibility and autonomy average score"="School responsibility and autonomy average score",
                  "TIMSS - Mathematics  Achievement, Grade 4"="TIMSS - Mathematics  Achievement, Grade 4",
                  "TIMSS - Mathematics Achievement, Grade 8"="TIMSS - Mathematics Achievement, Grade 8",
                  "TIMSS - Science  Achievement, Grade 4"="TIMSS - Science  Achievement, Grade 4",
                  "TIMSS - Science  Achievement, Grade 8"="TIMSS - Science  Achievement, Grade 8",
                  "Total public expenditure on educational institutions as % of GDP - all levels"="Total public expenditure on educational institutions as % of GDP - all levels",
                  "Unemployment of those with tertiary level education over total unemployment"="Unemployment of those with tertiary level education over total unemployment"
                ),selected = "Human Development Index"),
    column(offset=0,width=12,sliderInput("range","Years of Interest",min=1990,max=2014,value=c(1990,2014),sep="",width=350)),
    br(),
    h3("Select countries for comparisons"),
    selectInput("cnt","Selected Country",
                c("ALGERIA"="ALGERIA",
                  "ARGENTINA"="ARGENTINA",
                  "AUSTRALIA"="AUSTRALIA",
                  "AUSTRIA"="AUSTRIA",
                  "BELGIUM"="BELGIUM",
                  "BRAZIL"="BRAZIL",
                  "BULGARIA"="BULGARIA",
                  "CANADA"="CANADA",
                  "CHILE"="CHILE",
                  "CHINA"="CHINA",
                  "COLOMBIA"="COLOMBIA",
                  "CZECH.REPUBLIC"="CZECH.REPUBLIC",
                  "DENMARK"="DENMARK",
                  "EGYPT"="EGYPT",
                  "FINLAND"="FINLAND",
                  "FRANCE"="FRANCE",
                  "GERMANY"="GERMANY",
                  "GHANA"="GHANA",
                  "GREECE"="GREECE",
                  "HONG.KONG.CHINA"="HONG.KONG.CHINA",
                  "HUNGARY"="HUNGARY",
                  "INDIA"="INDIA",
                  "INDONESIA"="INDONESIA",
                  "IRELAND"="IRELAND",
                  "ISRAEL"="ISRAEL",
                  "ITALY"="ITALY",
                  "JAPAN"="JAPAN",
                  "KOREA"="KOREA",
                  "MEXICO"="MEXICO",
                  "NETHERLANDS"="NETHERLANDS",
                  "NEW.ZEALAND"="NEW.ZEALAND",
                  "NIGERIA"="NIGERIA",
                  "NORWAY"="NORWAY",
                  "POLAND"="POLAND",
                  "PORTUGAL"="PORTUGAL",
                  "QATAR"="QATAR",
                  "ROMANIA"="ROMANIA",
                  "RUSSIA"="RUSSIA",
                  "SAUDI.ARABIA"="SAUDI.ARABIA",
                  "SINGAPORE"="SINGAPORE",
                  "SLOVAKIA"="SLOVAKIA",
                  "SOUTH.AFRICA"="SOUTH.AFRICA",
                  "SPAIN"="SPAIN",
                  "SWEDEN"="SWEDEN",
                  "SWITZERLAND"="SWITZERLAND",
                  "THAILAND"="THAILAND",
                  "TURKEY"="TURKEY",
                  "UKRAINE"="UKRAINE",
                  "UNITED.KINGDOM"="UNITED.KINGDOM",
                  "UNITED.STATES"="UNITED.STATES",
                  "YEMEN"="YEMEN"
                  ),selected = "SINGAPORE"),
    selectInput("cnt2","Reference Country for comparison",
                c("ALGERIA"="ALGERIA",
                  "ARGENTINA"="ARGENTINA",
                  "AUSTRALIA"="AUSTRALIA",
                  "AUSTRIA"="AUSTRIA",
                  "BELGIUM"="BELGIUM",
                  "BRAZIL"="BRAZIL",
                  "BULGARIA"="BULGARIA",
                  "CANADA"="CANADA",
                  "CHILE"="CHILE",
                  "CHINA"="CHINA",
                  "COLOMBIA"="COLOMBIA",
                  "CZECH.REPUBLIC"="CZECH.REPUBLIC",
                  "DENMARK"="DENMARK",
                  "EGYPT"="EGYPT",
                  "FINLAND"="FINLAND",
                  "FRANCE"="FRANCE",
                  "GERMANY"="GERMANY",
                  "GHANA"="GHANA",
                  "GREECE"="GREECE",
                  "HONG.KONG.CHINA"="HONG.KONG.CHINA",
                  "HUNGARY"="HUNGARY",
                  "INDIA"="INDIA",
                  "INDONESIA"="INDONESIA",
                  "IRELAND"="IRELAND",
                  "ISRAEL"="ISRAEL",
                  "ITALY"="ITALY",
                  "JAPAN"="JAPAN",
                  "KOREA"="KOREA",
                  "MEXICO"="MEXICO",
                  "NETHERLANDS"="NETHERLANDS",
                  "NEW.ZEALAND"="NEW.ZEALAND",
                  "NIGERIA"="NIGERIA",
                  "NORWAY"="NORWAY",
                  "POLAND"="POLAND",
                  "PORTUGAL"="PORTUGAL",
                  "QATAR"="QATAR",
                  "ROMANIA"="ROMANIA",
                  "RUSSIA"="RUSSIA",
                  "SAUDI.ARABIA"="SAUDI.ARABIA",
                  "SINGAPORE"="SINGAPORE",
                  "SLOVAKIA"="SLOVAKIA",
                  "SOUTH.AFRICA"="SOUTH.AFRICA",
                  "SPAIN"="SPAIN",
                  "SWEDEN"="SWEDEN",
                  "SWITZERLAND"="SWITZERLAND",
                  "THAILAND"="THAILAND",
                  "TURKEY"="TURKEY",
                  "UKRAINE"="UKRAINE",
                  "UNITED.KINGDOM"="UNITED.KINGDOM",
                  "UNITED.STATES"="UNITED.STATES",
                  "YEMEN"="YEMEN"
                ),selected = "FINLAND"),
    br(),
    
    h3("Table of values for Selected comparisons"),
    tableOutput("tablE")
  ),
  
  
  mainPanel(
    tabsetPanel(
      tabPanel(
        "About this application",
        h3("About the dataset"),
        p("This dataset was taken from ",
        a("The Learning Curve,",href="http://thelearningcurve.pearson.com/databank/education-input-indicators"),
        "a global project which collects government inputs, outputs and socio-economic profiles of their education system."),
        p(
          "There are 39 education input/output/socioeconomic variables of 51 countries collected between
          the period of 1990 - 2014 by The Learning Curve. These variables ranged from the outputs (like annual average wage, 
          percentage of labour force with tertiary qulifications), inputs (teacher-pupil ratios) to socioeconomic factors (like 
          GDP and GINI indices). You can look at the data at the last tab of this app."
        ),
        # br(),
        h3("How to use Education Trends (1990 - 2014)"),
        p(
          "In the side-bar to the left are the main controls." 
          ),
        p(
          "Select an ", strong("Education Indicator "),"and the corrosponding ",strong("Years of Interest"), 
          "from the drop-down menu to the left and a ", strong("COUNTRY")," to analyse. Select also a ",
          strong("Reference Country for comparison"),". The table of values will appear
          in the sidebar below the controls."
        ),
        p(
          "Navigate to the tabset next to this labelled ", em("Education Trends (1990 - 2014)")
          ,". The ",strong("description of the Pearson Education Indicator"),"is automatically displayed. Regression
          lines of the time series of the selected country and reference countries are displayed.
           You may understand the gradient of the regression lines to mean the rate of change of 
          the indicator per year." 
        ),
        p(
          "A ggplot with the STATA theme from ", strong("library(ggthemes)")," is displayed showing how the two countries have faired in the
          indicator chosen over the time-frame chosen."
        ),
        p(
          "Finally, the graph is programmed to allow for you to ",strong("CLICK, "), 
          strong("DOUBLE-CLICK"), " or hover over the graph. The respective data 
          are displayed in the grey areas beneath the graph."
        ),
        p(
          "The data received from the ", strong("CLICK")," and ", strong("DOUBLE-CLICK"),
          " are calculated to provide a line. This gives the convenience of studying points
          or lines during the analysis."
        ),
        h3("How to use Snapshot Analysis"),
        p(
          strong("Snapshot Analysis")," is a tool used to correlate two Education indicators
          of the 51 countries in a chosen year."
        ),
        p(
          "First, select a year using the ", em("numericInput"), " tool and a secondary 
          indicator (y-axis). The primary indicator is the x-axis. A best-fit line is 
          created for the two variables in the chosen year and the R-squared statistic is 
          displayed."
        ),
        p(
          "If a given data catches your attention in the tab, click and drag around the point
          or points, i.e. brush the points, and the details of the countries will be displayed 
          in the panel below."
        ),
        p(
          " - ", em("Luo Kangshun, Andy")
        )
                ),
      
      tabPanel("Education Trends (1990 - 2014)",
               br(),
               h4("Description of Indicator"),
               p(h6(textOutput("des"))),
               br(),
               h4("Time series inferences"),
               column(width=5,verbatimTextOutput("llma")), 
               column(width=5,verbatimTextOutput("llmb")),
               #plot the ggplot
               column(width=12,plotOutput("ploT",  click="ploT_click",dblclick = "ploT_dblclick",hover="ploT_hover", brush = "ploT_brush")),
               br(),br(),br(),
               
               
               column(width=4,h4("HOVER data"), align="center"),
               column(width=4,h4("CLICK data"), align="center"),
               column(width=4,h4("DOUBLE-CLICK data"), align="center"),
               
               
               column(width=4,p(h6(verbatimTextOutput("hover")))),
               column(width=4,p(h6(verbatimTextOutput("click")))),
               column(width=4,p(h6(verbatimTextOutput("dblclick")))),
               br(),
               column(width=12,h4("Line formed between CLICK and DOUBLE-CLICK points")),
               column(width=12,p(h6(verbatimTextOutput("bflgrad"))))
               ),
      tabPanel("Snapshot Analysis",
               # column(6, checkboxGroupInput("snapshot", label = h3("Segregation by: "), 
                                         # choices = list("Country" = 1, "Year" = 2), selected = 1)),
               br(),
               column(width=3,numericInput("snapshot","Select Year to snapshot", min=1990,max=2013,step=1,value = 2010)),
               column(width=9,selectInput("edi2","Select Secondary Indicator to correlate",
                           c("Average annual gross wage (US$)"="Average annual gross wage (US$)",
                             "Citations H index"="Citations H index",
                             "Corruption Perceptions Index"="Corruption Perceptions Index",
                             "GDP per capita (US$PPP)"="GDP per capita (US$PPP)",
                             "Gini index"="Gini index",
                             "Government responsibility for informing parents about school choice. Primary and lower secondary levels"="Government responsibility for informing parents about school choice. Primary and lower secondary levels",
                             "Grade 4 - TIMSS"="Grade 4 - TIMSS",
                             "Grade 8 - PISA"="Grade 8 - PISA",
                             "Grade 8 - TIMSS"="Grade 8 - TIMSS",
                             "Health Index"="Health Index",
                             "Homicide per 100,000 people"="Homicide per 100,000 people",
                             "Human Development Index"="Human Development Index",
                             "Index of school responsibility for curriculum and assessment"="Index of school responsibility for curriculum and assessment",
                             "Labour force. Tertiary attainment (%)"="Labour force. Tertiary attainment (%)",
                             "Mean socio-economic background of parents"="Mean socio-economic background of parents",
                             "Number of jailed population per 100,000 people"="Number of jailed population per 100,000 people",
                             "Overall productivity of labour (GDP at US$PPP per worker)"="Overall productivity of labour (GDP at US$PPP per worker)",
                             "Parental expectations are characterised by pressure on the school to achieve high academic standards among students"="Parental expectations are characterised by pressure on the school to achieve high academic standards among students",
                             "PIAAC- Literacy proficiency"="PIAAC- Literacy proficiency",
                             "PIAAC- Numeracy proficiency"="PIAAC- Numeracy proficiency",
                             "PIAAC average score"="PIAAC average score",
                             "PIRLS - Reading Literacy Achievement, Grade 4"="PIRLS - Reading Literacy Achievement, Grade 4",
                             "PISA - Mathematics literacy, Grade 8"="PISA - Mathematics literacy, Grade 8",
                             "PISA - Overall reading literacy, Grade 8"="PISA - Overall reading literacy, Grade 8",
                             "PISA - Science literacy, Grade 8"="PISA - Science literacy, Grade 8",
                             "Pre-primary entrance age"="Pre-primary entrance age",
                             "Public expenditure on education as % of total government expenditure"="Public expenditure on education as % of total government expenditure",
                             "Public expenditure per pupil as % of GDP per capita. All levels"="Public expenditure per pupil as % of GDP per capita. All levels",
                             "Pupil-teacher ratio. Primary school"="Pupil-teacher ratio. Primary school",
                             "Pupil-teacher ratio. Secondary school"="Pupil-teacher ratio. Secondary school",
                             "Recorded unemployment (%)"="Recorded unemployment (%)",
                             "School life expectancy (Primary to tertiary)"="School life expectancy (Primary to tertiary)",
                             "School responsibility and autonomy average score"="School responsibility and autonomy average score",
                             "TIMSS - Mathematics  Achievement, Grade 4"="TIMSS - Mathematics  Achievement, Grade 4",
                             "TIMSS - Mathematics Achievement, Grade 8"="TIMSS - Mathematics Achievement, Grade 8",
                             "TIMSS - Science  Achievement, Grade 4"="TIMSS - Science  Achievement, Grade 4",
                             "TIMSS - Science  Achievement, Grade 8"="TIMSS - Science  Achievement, Grade 8",
                             "Total public expenditure on educational institutions as % of GDP - all levels"="Total public expenditure on educational institutions as % of GDP - all levels",
                             "Unemployment of those with tertiary level education over total unemployment"="Unemployment of those with tertiary level education over total unemployment"
                           ),selected = "Health Index")),
               column(width=12,verbatimTextOutput("llmc")),
               column(width=12,plotOutput("plOt",hover="plOt_hover",click="plOt_click",dblclick = "plOt_dblclick",brush="plOt_brush")),
               
               column(width=12,verbatimTextOutput("brush_info")) 
               
      ),
      tabPanel("Education Data",
               br(),
        column(width=4,selectInput("cnt3","Select COUNTRY for display",
                                   c("ALGERIA"="ALGERIA",
                                     "ARGENTINA"="ARGENTINA",
                                     "AUSTRALIA"="AUSTRALIA",
                                     "AUSTRIA"="AUSTRIA",
                                     "BELGIUM"="BELGIUM",
                                     "BRAZIL"="BRAZIL",
                                     "BULGARIA"="BULGARIA",
                                     "CANADA"="CANADA",
                                     "CHILE"="CHILE",
                                     "CHINA"="CHINA",
                                     "COLOMBIA"="COLOMBIA",
                                     "CZECH.REPUBLIC"="CZECH.REPUBLIC",
                                     "DENMARK"="DENMARK",
                                     "EGYPT"="EGYPT",
                                     "FINLAND"="FINLAND",
                                     "FRANCE"="FRANCE",
                                     "GERMANY"="GERMANY",
                                     "GHANA"="GHANA",
                                     "GREECE"="GREECE",
                                     "HONG.KONG.CHINA"="HONG.KONG.CHINA",
                                     "HUNGARY"="HUNGARY",
                                     "INDIA"="INDIA",
                                     "INDONESIA"="INDONESIA",
                                     "IRELAND"="IRELAND",
                                     "ISRAEL"="ISRAEL",
                                     "ITALY"="ITALY",
                                     "JAPAN"="JAPAN",
                                     "KOREA"="KOREA",
                                     "MEXICO"="MEXICO",
                                     "NETHERLANDS"="NETHERLANDS",
                                     "NEW.ZEALAND"="NEW.ZEALAND",
                                     "NIGERIA"="NIGERIA",
                                     "NORWAY"="NORWAY",
                                     "POLAND"="POLAND",
                                     "PORTUGAL"="PORTUGAL",
                                     "QATAR"="QATAR",
                                     "ROMANIA"="ROMANIA",
                                     "RUSSIA"="RUSSIA",
                                     "SAUDI.ARABIA"="SAUDI.ARABIA",
                                     "SINGAPORE"="SINGAPORE",
                                     "SLOVAKIA"="SLOVAKIA",
                                     "SOUTH.AFRICA"="SOUTH.AFRICA",
                                     "SPAIN"="SPAIN",
                                     "SWEDEN"="SWEDEN",
                                     "SWITZERLAND"="SWITZERLAND",
                                     "THAILAND"="THAILAND",
                                     "TURKEY"="TURKEY",
                                     "UKRAINE"="UKRAINE",
                                     "UNITED.KINGDOM"="UNITED.KINGDOM",
                                     "UNITED.STATES"="UNITED.STATES",
                                     "YEMEN"="YEMEN"
                                   ),selected = "SINGAPORE")),
        column(width=4,selectInput("edi3","Select Indicator to display",
                                   c("Average annual gross wage (US$)"="Average annual gross wage (US$)",
                                     "Citations H index"="Citations H index",
                                     "Corruption Perceptions Index"="Corruption Perceptions Index",
                                     "GDP per capita (US$PPP)"="GDP per capita (US$PPP)",
                                     "Gini index"="Gini index",
                                     "Government responsibility for informing parents about school choice. Primary and lower secondary levels"="Government responsibility for informing parents about school choice. Primary and lower secondary levels",
                                     "Grade 4 - TIMSS"="Grade 4 - TIMSS",
                                     "Grade 8 - PISA"="Grade 8 - PISA",
                                     "Grade 8 - TIMSS"="Grade 8 - TIMSS",
                                     "Health Index"="Health Index",
                                     "Homicide per 100,000 people"="Homicide per 100,000 people",
                                     "Human Development Index"="Human Development Index",
                                     "Index of school responsibility for curriculum and assessment"="Index of school responsibility for curriculum and assessment",
                                     "Labour force. Tertiary attainment (%)"="Labour force. Tertiary attainment (%)",
                                     "Mean socio-economic background of parents"="Mean socio-economic background of parents",
                                     "Number of jailed population per 100,000 people"="Number of jailed population per 100,000 people",
                                     "Overall productivity of labour (GDP at US$PPP per worker)"="Overall productivity of labour (GDP at US$PPP per worker)",
                                     "Parental expectations are characterised by pressure on the school to achieve high academic standards among students"="Parental expectations are characterised by pressure on the school to achieve high academic standards among students",
                                     "PIAAC- Literacy proficiency"="PIAAC- Literacy proficiency",
                                     "PIAAC- Numeracy proficiency"="PIAAC- Numeracy proficiency",
                                     "PIAAC average score"="PIAAC average score",
                                     "PIRLS - Reading Literacy Achievement, Grade 4"="PIRLS - Reading Literacy Achievement, Grade 4",
                                     "PISA - Mathematics literacy, Grade 8"="PISA - Mathematics literacy, Grade 8",
                                     "PISA - Overall reading literacy, Grade 8"="PISA - Overall reading literacy, Grade 8",
                                     "PISA - Science literacy, Grade 8"="PISA - Science literacy, Grade 8",
                                     "Pre-primary entrance age"="Pre-primary entrance age",
                                     "Public expenditure on education as % of total government expenditure"="Public expenditure on education as % of total government expenditure",
                                     "Public expenditure per pupil as % of GDP per capita. All levels"="Public expenditure per pupil as % of GDP per capita. All levels",
                                     "Pupil-teacher ratio. Primary school"="Pupil-teacher ratio. Primary school",
                                     "Pupil-teacher ratio. Secondary school"="Pupil-teacher ratio. Secondary school",
                                     "Recorded unemployment (%)"="Recorded unemployment (%)",
                                     "School life expectancy (Primary to tertiary)"="School life expectancy (Primary to tertiary)",
                                     "School responsibility and autonomy average score"="School responsibility and autonomy average score",
                                     "TIMSS - Mathematics  Achievement, Grade 4"="TIMSS - Mathematics  Achievement, Grade 4",
                                     "TIMSS - Mathematics Achievement, Grade 8"="TIMSS - Mathematics Achievement, Grade 8",
                                     "TIMSS - Science  Achievement, Grade 4"="TIMSS - Science  Achievement, Grade 4",
                                     "TIMSS - Science  Achievement, Grade 8"="TIMSS - Science  Achievement, Grade 8",
                                     "Total public expenditure on educational institutions as % of GDP - all levels"="Total public expenditure on educational institutions as % of GDP - all levels",
                                     "Unemployment of those with tertiary level education over total unemployment"="Unemployment of those with tertiary level education over total unemployment"
                                   ),selected = "Human Development Index")),
         br(),
        tableOutput("tablE2")
      )
      
    )
  )
))
